---
title: "Stimuli Preprocessing"
output:
  github_document:
    toc: true
    fig_width: 10.08
    fig_height: 6
editor_options:
  chunk_output_type: console
---

```{r, echo = FALSE, warning=FALSE, message=FALSE}
# options and parameters
options(digits = 3)

knitr::opts_chunk$set(
  collapse = TRUE,
  dpi = 450,
  fig.path = "./figures/"
)
```


```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(easystats)
library(ggimage)
```

```{r, warning=FALSE, message=FALSE, fig.height=10, fig.width=10}
# 1. NEVER spaces or weird characters in paths/filenames etc
# 2. When possible, always work with relative paths and not absoltue (C://dom/) 
# so that it's reproducible
# Remove the comment above once it's read as a reading check
df <- read.csv("AMFD_norms.csv") |> 
  filter(FType == 0) |> 
  mutate(Gender = ifelse(Gender_cat == 2, "M", "F"),
         File = paste0("AMFD/N", Gender, "-", PhotoID, ".jpg"))


df_extremes <- df |> 
  filter(abs(standardize(Attract_mean)) > 1.5 | 
           abs(standardize(Trust_mean)) > 2)


ggplot(df, aes(x = Attract_mean, y=Trust_mean)) +
  geom_point(aes(color=Gender)) +
  geom_image(data=df_extremes, aes(image=File), size=0.1) + 
  geom_smooth(aes(color=Gender), method="lm", se=FALSE) +
  theme_modern() +
  labs(x = "Attractiveness", y = "Trust")
```
